openapi: 3.0.0
info:
  description: Mock API for vue-typescript-admin-template.
  version: 1.0.1
  title: Mock API
  contact:
    email: armourcy@email.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: /mock-api/v1
paths:
  /users:
    get:
      tags:
        - users
      summary: Get Users list
      description: Return a list of users
      operationId: getUsers
      security:
        - AccessTokenAuth: []
      parameters:
        - name: name
          in: query
          description: Used to filter users by matched username substring
          scheme:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              scheme:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                  data:
                    type: object
                    properties:
                      items:
                        type:
                          array
                        items:
                          $ref: '#/components/schemas/User'
        401:
          $ref: '#/components/responses/Unauthorized'
  /users/register:
    post:
      tags:
        - users
      